name: Ein Monat
favicon: null
layout_spectrum: 0.5427633468061686
typography_spectrum: 0.899386879755184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5868521011434495
  lightness: 0.5373096440453082
  saturation: 0.38794631557539105
  rhythmicContrast: 0.9674441202078015
purpose: []
