name: Ein Monat
favicon: null
layout_spectrum: 0.59335
typography_spectrum: 0.68522
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffed00'
    - '#1a171b'
    - '#817e60'
    - '#cfc324'
    - '#a8a042'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
